augs:
  LR: 0.5
  UD: 0.0
  brightness: 0.25
  color_p: 0.5
  contrast: 0.1
  crop_size: null
  dali: false
  degrees: 10
  grayscale: 0.5
  hue: 0.1
  normalization:
    N: 616891852800
    mean:
    - 0.425280944716674
    - 0.43149049968550984
    - 0.3634010999177969
    std:
    - 0.2179858888556464
    - 0.2206349264361932
    - 0.21700557077024724
  pad: null
  random_resize: false
  resize:
  - 224
  - 224
  saturation: 0.1
cmap: deepethogram
compute:
  batch_size: 8
  dali: false
  distributed: false
  fp16: false
  gpu_id: 0
  max_batch_size: 128
  metrics_workers: 0
  min_batch_size: 8
  num_workers: 3
control_arrow_jump: 31
flow_generator:
  arch: TinyMotionNet
  flow_loss: MotionNet
  flow_max: 10
  flow_sparsity: false
  input_images: 11
  loss: MotionNet
  max: 5
  n_rgb: 11
  smooth_weight_multiplier: 1.0
  sparsity_weight: 0.0
  type: flow_generator
  weights: pretrained
label_view_width: 31
log:
  level: info
notes: null
postprocessor:
  min_bout_length: 10
  type: min_bout_per_behavior
prediction_opacity: 0.2
project:
  class_names:
  - background
  - Onnest
  - Offnest
  - ABN
  - Carryingpups
  - Selfgrooming
  - Eat_drink
  - Kicking
  - Groomingpups
  - Build
  config_file: project_config.yaml
  data_path: D:\LBN\Maternal_auto_classification_train_deepethogram\DATA
  labeler: null
  model_path: D:\LBN\Maternal_auto_classification_train_deepethogram\models
  name: Maternal_auto_classification
  path: D:\LBN\Maternal_auto_classification_train_deepethogram
  pretrained_path: D:\LBN\Maternal_auto_classification_train_deepethogram\models\pretrained_models
reload:
  latest: false
  overwrite_cfg: false
  weights: D:\LBN\Maternal_auto_classification_train_deepethogram\models\pretrained_models\200221_115158_TinyMotionNet\checkpoint.pt
run:
  dir: D:\LBN\Maternal_auto_classification_train_deepethogram\models\250602_134424_flow_generator_train
  model: flow_generator
  type: train
sequence:
  filter_length: 15
split:
  file: null
  reload: true
  train_val_test:
  - 0.8
  - 0.2
  - 0.0
train:
  early_stopping_begins: 0
  label_smoothing: 0.05
  loss_gamma: 1.0
  loss_weight_exp: 1.0
  lr: 0.0001
  milestones:
  - 50
  - 100
  - 150
  - 200
  - 250
  - 300
  min_lr: 5.0e-07
  num_epochs: 10
  oversampling_exp: 0.0
  patience: 3
  reduction_factor: 0.1
  regularization:
    alpha: 1.0e-05
    beta: 0.001
    style: l2_sp
  scheduler: plateau
  steps_per_epoch:
    test: 20
    train: 1000
    val: 200
  stopping_type: learning_rate
  viz_examples: 10
  viz_metrics: true
  weight_loss: true
unlabeled_alpha: 0.1
vertical_arrow_jump: 3
