augs:
  LR: 0.5
  UD: 0.0
  brightness: 0.25
  color_p: 0.5
  contrast: 0.1
  crop_size: null
  dali: false
  degrees: 10
  grayscale: 0.5
  hue: 0.1
  normalization:
    N: 616891852800
    mean:
    - 0.425280944716674
    - 0.43149049968550984
    - 0.3634010999177969
    std:
    - 0.2179858888556464
    - 0.2206349264361932
    - 0.21700557077024724
  pad: null
  random_resize: false
  resize:
  - 224
  - 224
  saturation: 0.1
cmap: deepethogram
compute:
  batch_size: 8
  dali: false
  distributed: false
  fp16: false
  gpu_id: 0
  max_batch_size: 128
  metrics_workers: 0
  min_batch_size: 8
  num_workers: 3
control_arrow_jump: 31
feature_extractor:
  arch: resnet18
  curriculum: false
  dropout_p: 0.25
  final_activation: sigmoid
  final_bn: false
  fusion: average
  inputs: both
  n_flows: 10
  n_rgb: 1
  sampler: null
  sampling_ratio: null
  weights: pretrained
inference:
  directory_list:
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\CONT-2024-05-06_21-00-34
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\CONT-2024-05-06_22-00-34
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\CONT-2024-05-06_22-10-34
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\CONT-2024-05-06_22-40-35
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\CONT-2024-05-06_23-20-35
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\CONT-2024-05-06_23-40-35
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\CONT-2024-05-07_04-00-35
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\CONT-2024-05-07_04-50-35
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\CONT-2024-05-07_05-30-35
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\CONT-2024-05-07_06-20-35
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\CONT-2024-05-07_06-50-35
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\CONT-2024-05-07_07-10-35
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\CONT-2024-05-07_07-20-35
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\CONT-2024-05-07_20-56-20
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\CONT-2024-05-07_22-06-20
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\CONT-2024-05-07_22-26-20
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\CONT-2024-05-07_22-46-20
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\CONT-2024-05-07_23-06-20
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\CONT-2024-05-07_23-36-20
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\CONT-2024-05-07_23-46-20
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\CONT-2024-05-08_04-06-21
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\CONT-2024-05-08_04-16-21
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\CONT-2024-05-08_04-46-21
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\CONT-2024-05-08_05-06-21
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\CONT-2024-05-08_06-36-21
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\CONT-2024-05-08_22-06-23
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\CONT-2024-05-08_23-46-23
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\CONT-2024-05-09_05-16-23
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\CONT-2024-05-09_06-56-23
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\Cage1-LBN-2024-08-30_20-14-40
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\Cage1-LBN-2024-08-30_20-24-40
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\Cage1-LBN-2024-08-30_20-34-40
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\Cage1-LBN-2024-08-30_21-44-40
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\Cage1-LBN-2024-08-30_21-44-40_blur
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\Cage1-LBN-2024-08-30_21-44-40_bright_contrast
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\Cage1-LBN-2024-08-30_21-44-40_combo123
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\Cage1-LBN-2024-08-30_21-44-40_combo124
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\Cage1-LBN-2024-08-30_21-44-40_combo234
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\Cage1-LBN-2024-08-30_21-44-40_flip
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\Cage1-LBN-2024-08-30_21-44-40_zoom_crop
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\Cage1-LBN-2024-08-30_22-14-40
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\Cage1-LBN-2024-08-30_22-14-40_blur
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\Cage1-LBN-2024-08-30_22-14-40_bright_contrast
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\Cage1-LBN-2024-08-30_22-14-40_combo123
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\Cage1-LBN-2024-08-30_22-14-40_combo124
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\Cage1-LBN-2024-08-30_22-14-40_combo234
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\Cage1-LBN-2024-08-30_22-14-40_flip
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\Cage1-LBN-2024-08-30_22-14-40_zoom_crop
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\Cage1-LBN-2024-08-30_22-54-40
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\Cage1-LBN-2024-08-30_23-24-40
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\Cage1-LBN-2024-08-31_04-44-40
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\Cage1-LBN-2024-08-31_05-04-40
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\Cage1-LBN-2024-08-31_05-24-40
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\Cage1-LBN-2024-08-31_07-14-40
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\Cage1-LBN-2024-09-03_22-21-56
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\Cage1-LBN-2024-09-03_23-41-56
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\Cage2-LBN-2024-12-08_20-38-34
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\Cage2-LBN-2024-12-08_22-48-35
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\Cage2-LBN-2024-12-08_22-58-35
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\Cage2-LBN-2024-12-08_22-58-35_blur
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\Cage2-LBN-2024-12-08_22-58-35_bright_contrast
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\Cage2-LBN-2024-12-08_22-58-35_combo123
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\Cage2-LBN-2024-12-08_22-58-35_combo124
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\Cage2-LBN-2024-12-08_22-58-35_combo234
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\Cage2-LBN-2024-12-08_22-58-35_flip
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\Cage2-LBN-2024-12-08_22-58-35_zoom_crop
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\Cage2-LBN-2024-12-09_05-48-35
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\Cage2-LBN-2024-12-09_07-08-35
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\Cage2-LBN-2024-12-09_20-48-38
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\Cage2-LBN-2024-12-09_21-48-38
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\Cage6-CONT-2024-12-12_20-02-17
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\Cage6-CONT-2024-12-12_20-12-17
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\Cage6-CONT-2024-12-12_20-22-17
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\Cage6-CONT-2024-12-12_20-32-17
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\Cage6-CONT-2024-12-12_20-42-17
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\Cage6-CONT-2024-12-12_20-52-17
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\Cage6-CONT-2024-12-12_21-02-17
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\Cage6-CONT-2024-12-12_21-12-17
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\Cage6-CONT-2024-12-12_21-22-17
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\Cage6-CONT-2024-12-12_21-32-17
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\Cage6-CONT-2024-12-12_21-42-17
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\Cage6-CONT-2024-12-12_21-52-17
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\Cage6-CONT-2024-12-12_22-02-17
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\Cage6-CONT-2024-12-12_22-12-17
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\Cage6-CONT-2024-12-12_22-22-17
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\Cage6-CONT-2024-12-12_22-32-17
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\Cage6-CONT-2024-12-12_22-42-17
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\Cage6-CONT-2024-12-12_22-52-17
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\Cage6-CONT-2024-12-12_23-02-17
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\Cage6-CONT-2024-12-12_23-12-17
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\Cage6-CONT-2024-12-12_23-22-17
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\Cage6-CONT-2024-12-12_23-32-17
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\Cage6-CONT-2024-12-12_23-42-17
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\Cage6-CONT-2024-12-12_23-52-17
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\Cage6-CONT-2024-12-13_00-02-17
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\Cage6-CONT-2024-12-13_04-02-17
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\Cage6-CONT-2024-12-13_04-12-17
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\Cage6-CONT-2024-12-13_04-22-17
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\Cage6-CONT-2024-12-13_04-32-17
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\Cage6-CONT-2024-12-13_04-42-17
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\Cage6-CONT-2024-12-13_04-52-17
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\Cage6-CONT-2024-12-13_05-02-17
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\Cage6-CONT-2024-12-13_05-12-17
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\Cage6-CONT-2024-12-13_05-22-17
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\Cage6-CONT-2024-12-13_05-32-17
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\Cage6-CONT-2024-12-13_05-42-17
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\Cage6-CONT-2024-12-13_05-52-17
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\CageA-LBN-2024-07-05_20-03-20
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\CageA-LBN-2024-07-05_20-23-20
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\CageA-LBN-2024-07-05_20-33-20
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\CageA-LBN-2024-07-05_20-43-20
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\CageA-LBN-2024-07-05_20-53-20
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\CageA-LBN-2024-07-05_21-03-20
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\CageA-LBN-2024-07-05_21-13-20
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\CageA-LBN-2024-07-05_21-23-20
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\CageA-LBN-2024-07-05_21-33-20
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\CageA-LBN-2024-07-05_21-43-20
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\CageA-LBN-2024-07-05_21-53-20
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\CageA-LBN-2024-07-05_22-03-20
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\CageA-LBN-2024-07-05_22-13-20
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\CageA-LBN-2024-07-05_22-23-20
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\CageA-LBN-2024-07-05_22-33-20
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\CageA-LBN-2024-07-05_22-43-20
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\CageA-LBN-2024-07-05_22-53-20
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\CageA-LBN-2024-07-05_23-03-20
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\CageA-LBN-2024-07-05_23-13-20
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\CageA-LBN-2024-07-05_23-23-20
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\CageA-LBN-2024-07-05_23-33-20
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\CageA-LBN-2024-07-05_23-43-20
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\CageA-LBN-2024-07-05_23-53-20
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\CageA-LBN-2024-07-06_04-03-20
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\CageA-LBN-2024-07-06_04-13-20
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\CageA-LBN-2024-07-06_04-23-20
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\CageA-LBN-2024-07-06_04-33-20
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\CageA-LBN-2024-07-06_04-43-20
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\CageA-LBN-2024-07-06_04-53-20
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\CageA-LBN-2024-07-06_05-03-20
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\CageA-LBN-2024-07-06_05-13-20
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\CageA-LBN-2024-07-06_05-23-20
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\CageA-LBN-2024-07-06_05-33-20
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\CageA-LBN-2024-07-06_05-33-20_blur
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\CageA-LBN-2024-07-06_05-33-20_bright_contrast
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\CageA-LBN-2024-07-06_05-33-20_combo123
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\CageA-LBN-2024-07-06_05-33-20_combo124
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\CageA-LBN-2024-07-06_05-33-20_combo234
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\CageA-LBN-2024-07-06_05-33-20_flip
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\CageA-LBN-2024-07-06_05-33-20_zoom_crop
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\CageA-LBN-2024-07-06_05-43-20
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\CageA-LBN-2024-07-06_05-53-21
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\CageA-LBN-2024-07-06_06-03-21
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\CageA-LBN-2024-07-06_06-13-21
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\CageA-LBN-2024-07-06_06-23-21
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\CageA-LBN-2024-07-06_06-33-21
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\CageA-LBN-2024-07-06_06-43-21
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\CageA-LBN-2024-07-06_06-53-21
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\CageA-LBN-2024-07-06_07-03-21
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\CageA-LBN-2024-07-06_07-13-21
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\CageA-LBN-2024-07-06_07-23-21
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\CageA-LBN-2024-07-06_07-33-21
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\CageA-LBN-2024-07-06_20-14-42
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\CageA-LBN-2024-07-06_21-54-42
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\CageA-LBN-2024-07-06_22-24-42
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\CageA-LBN-2024-07-06_23-04-42
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\CageA-LBN-2024-07-06_23-14-42
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\CageA-LBN-2024-07-07_04-54-43
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\CageA-LBN-2024-07-07_05-44-43
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\CageA-LBN-2024-07-07_06-14-43
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\CageA-LBN-2024-07-07_06-44-43
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\CageA-LBN-2024-07-07_06-54-43
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\CageA-LBN-2024-07-07_20-04-49
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\CageA-LBN-2024-07-07_20-24-49
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\CageA-LBN-2024-07-07_20-44-49
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\CageA-LBN-2024-07-07_21-04-49
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\CageA-LBN-2024-07-07_21-54-49
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\CageA-LBN-2024-07-07_22-54-49
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\CageA-LBN-2024-07-07_23-54-50
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\CageA-LBN-2024-07-07_23-54-50_blur
  - D:\LBN\Maternal_auto_classification_train_deepethogram\DATA\CageA-LBN-2024-07-07_23-54-50_bright_contrast
  ignore_error: true
  overwrite: true
  use_loaded_model_cfg: true
label_view_width: 31
log:
  level: info
notes: null
postprocessor:
  min_bout_length: 10
  type: min_bout_per_behavior
prediction_opacity: 0.2
project:
  class_names:
  - background
  - Onnest
  - Offnest
  - ABN
  - Carryingpups
  - Selfgrooming
  - Eat_drink
  - Kicking
  - Groomingpups
  - Build
  config_file: project_config.yaml
  data_path: D:\LBN\Maternal_auto_classification_train_deepethogram\DATA
  labeler: null
  model_path: D:\LBN\Maternal_auto_classification_train_deepethogram\models
  name: Maternal_auto_classification
  path: D:\LBN\Maternal_auto_classification_train_deepethogram
  pretrained_path: D:\LBN\Maternal_auto_classification_train_deepethogram\models\pretrained_models
reload:
  latest: false
  overwrite_cfg: false
run:
  dir: D:\LBN\Maternal_auto_classification_train_deepethogram\models\250603_160436_sequence_inference
  model: sequence
  type: inference
sequence:
  arch: tgmj
  bidirectional: false
  c_in: 1
  c_out: 8
  dropout_p: 0.5
  filter_length: 15
  final_bn: true
  hidden_dropout: 0.0
  hidden_size: 64
  input_dropout: 0.5
  input_type: features
  latent_name: null
  n_filters: 8
  nonlinear_classification: true
  nonoverlapping: true
  num_features: 128
  num_layers: 3
  output_name: null
  rnn_style: lstm
  sequence_length: 180
  soft_attn: true
  tgm_reduction: max
  weights: D:\LBN\Maternal_auto_classification_train_deepethogram\models\250603_145653_sequence_train\lightning_checkpoints\epoch=28-step=9685.ckpt
split:
  file: null
  reload: true
  train_val_test:
  - 0.9
  - 0.1
  - 0.0
train:
  loss_weight_exp: 1.0
  num_epochs: 100
  patience: 5
  regularization:
    alpha: 0.01
    style: l2
  steps_per_epoch:
    test: null
    train: 1000
    val: 1000
unlabeled_alpha: 0.1
vertical_arrow_jump: 3
