LR: 0.5
UD: 0.0
arch: hidden_two_stream
background_weight: 1.0
batch_size: 48
brightness: 0.25
classifier: resnet3d_34
config_file: null
contrast: 0.1
crop_size: !!python/tuple
- 224
- 224
curriculum: true
dali: true
data_dir: /media/jim/FASTER/kinetics700
dataset: kinetics
degrees: 10
distributed: true
dropout_p: 0
early_stopping_begins: null
final_activation: softmax
flow_generator: TinyMotionNet3D
flow_loss: MotionNet
flow_max: 10
flow_style: polar
fp16: false
fusion: average
gpu_id: 0
input_images: 11
inputs: rgb
lr: 0.0001
milestones:
- 50
- 100
- 150
- 200
- 250
- 300
min_lr: 5.0e-07
model: feature_extractor
model_dir: models
name: kinetics
normalization:
  flow:
    N: 2097152000000
    mean: null
    std: null
  rgb:
    N: 209715200000
    mean:
    - 0.4345759153366089
    - 0.39914101362228394
    - 0.37257176637649536
    std:
    - 0.2809292674064636
    - 0.27423909306526184
    - 0.27391594648361206
notes: degs_224_dali_nodropout_weightdecay
num_classes: 700
num_epochs: 1000
num_flows: 10
num_rgb: 11
num_workers: 2
pad: null
patience: 10
pos_weight: null
preset: null
project_dir: null
random_resize: false
reduction_factor: !!python/object/apply:numpy.core.multiarray.scalar
- !!python/object/apply:numpy.dtype
  args:
  - f8
  - 0
  - 1
  state: !!python/tuple
  - 3
  - <
  - null
  - null
  - null
  - -1
  - -1
  - 0
- !!binary |
  D0lIYhM91D8=
reload_split: true
resize: null
sampler: null
sampling_ratio: null
scheduler: plateau
should_overwrite_args: false
should_viz: true
spatial_only: true
splitfile: null
steps_per_epoch: 1000
steps_per_test_epoch: 20
steps_per_validation_epoch: 1000
stopping_type: plateau
train_val_test_split:
- 0.8
- 0.2
- 0.0
weight_decay: 0.0001
weight_loss: false
weights: null
