augs:
  LR: 0.5
  UD: 0.0
  brightness: 0.25
  contrast: 0.1
  crop_size: null
  degrees: 10
  grayscale: 0.5
  hue: 0.1
  normalization:
    N: 602063539200
    mean:
    - 0.4255179427333451
    - 0.4318805265255125
    - 0.36213819065404623
    std:
    - 0.21698254372191034
    - 0.2196990802354153
    - 0.21598310667194642
  pad: null
  random_resize: false
  resize:
  - 224
  - 224
  saturation: 0.1
cmap: deepethogram
compute:
  batch_size: 8
  dali: false
  distributed: false
  fp16: false
  gpu_id: 0
  max_batch_size: 128
  metrics_workers: 0
  min_batch_size: 8
  num_workers: 3
control_arrow_jump: 31
label_view_width: 31
log:
  level: info
notes: null
postprocessor:
  min_bout_length: 1
  type: min_bout_per_behavior
prediction_opacity: 0.2
project:
  class_names:
  - background
  - Onnest
  - Offnest
  - ABN
  - Carryingpups
  - Selfgrooming
  - Eat_drink
  - Kicking
  - Groomingpups
  - Build
  config_file: project_config.yaml
  data_path: D:\LBN\Maternal_auto_classification_TS7_deepethogram\DATA
  labeler: null
  model_path: D:\LBN\Maternal_auto_classification_TS7_deepethogram\models
  name: Maternal_auto_classification
  path: D:\LBN\Maternal_auto_classification_TS7_deepethogram
  pretrained_path: D:\LBN\Maternal_auto_classification_TS7_deepethogram\models\pretrained_models
reload:
  latest: false
  overwrite_cfg: false
run:
  dir: D:\LBN\Maternal_auto_classification_TS7_deepethogram\gui_logs\250528_164901
  model: null
  type: gui
sequence:
  filter_length: 15
split:
  file: null
  reload: true
  train_val_test:
  - 0.8
  - 0.2
  - 0.0
train:
  loss_weight_exp: 1.0
unlabeled_alpha: 0.1
vertical_arrow_jump: 3
