augs:
  LR: 0.5
  UD: 0.0
  brightness: 0.25
  color_p: 0.5
  contrast: 0.1
  crop_size: null
  dali: false
  degrees: 10
  grayscale: 0.5
  hue: 0.1
  normalization:
    N: 1276852377600
    mean:
    - 0.40560616330988664
    - 0.40903226014977145
    - 0.3720154588275182
    std:
    - 0.24422178855813376
    - 0.24576464877583507
    - 0.24317006853183584
  pad: null
  random_resize: false
  resize:
  - 224
  - 224
  saturation: 0.1
cmap: deepethogram
compute:
  batch_size: 8
  dali: false
  distributed: false
  fp16: false
  gpu_id: 0
  max_batch_size: 128
  metrics_workers: 0
  min_batch_size: 8
  num_workers: 8
control_arrow_jump: 31
inference:
  directory_list: []
  ignore_error: true
  overwrite: true
  use_loaded_model_cfg: true
label_view_width: 31
log:
  level: info
notes: null
postprocessor:
  min_bout_length: 10
  min_bout_per_behavior:
  - 5
  - 5
  - 5
  - 5
  - 5
  - 5
  - 5
  - 5
  - 5
  - 5
  type: min_bout_per_behavior
prediction_opacity: 0.2
project:
  class_names:
  - background
  - Onnest
  - Offnest
  - ABN
  - Carryingpups
  - Selfgrooming
  - Eat_drink
  - Kicking
  - Groomingpups
  - Build
  config_file: project_config.yaml
  data_path: D:\LBN\Maternal_auto_classification_TS7_deepethogram\DATA
  labeler: null
  model_path: D:\LBN\Maternal_auto_classification_TS7_deepethogram\models
  name: Maternal_auto_classification
  path: D:\LBN\Maternal_auto_classification_TS7_deepethogram
  pretrained_path: D:\LBN\Maternal_auto_classification_TS7_deepethogram\models\pretrained_models
reload:
  latest: false
  overwrite_cfg: false
run:
  dir: D:\LBN\Maternal_auto_classification_TS7_deepethogram\models\250606_150655_sequence_inference
  model: sequence
  type: inference
sequence:
  arch: tgmj
  bidirectional: false
  c_in: 1
  c_out: 8
  dropout_p: 0.5
  filter_length: 15
  final_bn: true
  hidden_dropout: 0.0
  hidden_size: 64
  input_dropout: 0.5
  input_type: features
  latent_name: null
  n_filters: 8
  nonlinear_classification: true
  nonoverlapping: true
  num_features: 128
  num_layers: 3
  output_name: null
  rnn_style: lstm
  sequence_length: 180
  soft_attn: true
  tgm_reduction: max
  weights: D:\LBN\Maternal_auto_classification_TS7_deepethogram\models\250603_145653_sequence_train\lightning_checkpoints\epoch=28-step=9685.ckpt
split:
  file: null
  reload: true
  train_val_test:
  - 0.9
  - 0.1
  - 0.0
train:
  loss_weight_exp: 1.0
  num_epochs: 100
  patience: 5
  regularization:
    alpha: 0.01
    style: l2
unlabeled_alpha: 0.1
vertical_arrow_jump: 3
